version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: flask_app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_HOST: db
      DB_DATABASE: flaskdb
      DB_USER: flaskuser
      DB_PASSWORD: flaskpassword
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
